# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtaButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('main_image_quote', models.TextField(blank=True, null=True)),
                ('main_image_quote_sub', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('meta_keywords', models.CharField(max_length=128)),
                ('meta_description', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(1, 'moderation'), (0, 'new'), (2, 'published')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'category'), (0, 'single'), (2, 'landing')], default=0)),
                ('show_in_homepage', models.IntegerField(choices=[(1, 'yes'), (0, 'no')], default=1)),
                ('view_order', models.IntegerField(null=True)),
                ('show_in_tags', models.IntegerField(null=True)),
                ('deleted', models.IntegerField(choices=[(1, 'yes'), (0, 'no')], default=0)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_users', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(related_name='_page_category_+', to='dashboard.Page')),
                ('keywords', models.ManyToManyField(related_name='keywords', to='dashboard.Keywords')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Page')),
                ('redirect_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirected_from', to='dashboard.Page')),
            ],
            options={
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('show_in_homepage', models.IntegerField(choices=[(1, 'yes'), (0, 'no')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('template_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.TemplateGroup')),
            ],
        ),
        migrations.AddField(
            model_name='tags',
            name='templates',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='dashboard.Templates'),
        ),
        migrations.AddField(
            model_name='page',
            name='templates',
            field=models.ManyToManyField(related_name='pages', to='dashboard.Templates'),
        ),
        migrations.AddField(
            model_name='ctabutton',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='dashboard.Page'),
        ),
    ]
